# ====================== Inputs ======================

filebeat.inputs:

  # --- Firewalls (Text/Syslog) ---
  - type: filestream
    enabled: true
    id: firewall-input
    paths:
      - /datasets/firewall/*.log
    fields:
      log_type: firewall
    fields_under_root: true
    pipeline: "fortigate-kv"
    ignore_older: 0s

  # --- Windows (JSON) ---
  - type: filestream
    enabled: true
    id: windows-input
    paths:
      - /datasets/windows/*.json
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          overwrite_keys: true
    fields:
      log_type: windows
    fields_under_root: true
    ignore_older: 0s

  # --- Linux (Text/Syslog) ---
  - type: filestream
    enabled: true
    id: linux-input
    paths:
      - /datasets/linux/*.log
    fields:
      log_type: linux
    fields_under_root: true
    ignore_older: 0s

  # --- Azure (JSON) ---
  - type: filestream
    enabled: true
    id: azure-input
    paths:
      - /datasets/azure/activity/*.json
      - /datasets/azure/signin/*.json
      - /datasets/azure/audit/*.json
      - /datasets/azure/firewall/*.json
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          overwrite_keys: true
    fields:
      log_type: azure
    fields_under_root: true
    ignore_older: 0s

  # --- AWS (JSON Data) ---
  - type: filestream
    enabled: true
    id: aws-json-input
    paths:
      - /datasets/aws/cloudtrail/*.json
      - /datasets/aws/guardduty/*.json
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          overwrite_keys: true
    fields:
      log_type: aws
    fields_under_root: true
    ignore_older: 0s

  # --- AWS (Plain Text / CSV Data) ---
  - type: filestream
    enabled: true
    id: aws-log-input
    paths:
      - /datasets/aws/vpcflow/*.log
      - /datasets/aws/s3access/*.log
    fields:
      log_type: aws
    fields_under_root: true
    ignore_older: 0s

# ====================== Output ======================
output.elasticsearch:
  hosts: ["http://es01:9200"]
  username: "elastic"
  password: "changeme"

# ====================== Kibana Setup ======================
setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"

# ====================== Processors ======================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ====================== Logging ======================
logging.level: info
logging.to_files: false
logging.to_stdout: true